feat: check_plain function support atom key
emqx/hocon pull request #95
Opened 2021-07-05 08:17 UTC by Rory-Z

2021-07-06 11:35 UTC, z8674558 submitted a review, later dismissed

2021-07-06 14:09 UTC, zmstone requested changes

2021-07-06 14:09 UTC, zmstone commented on src/hocon_schema.erl
> +atom(B) when is_binary(B) -> binary_to_atom(B, utf8).
to existing atom ?

2021-07-07 02:03 UTC, Rory-Z commented on src/hocon_schema.erl
> +atom(B) when is_binary(B) -> binary_to_atom(B, utf8).
Fixed

2021-07-07 04:29 UTC, zmstone commented on src/hocon_schema.erl
> +    Child = case maps:get(H, Conf, undefined) of
Catch error if it’s not a an existing atom, return undefined

2021-07-07 04:33 UTC, zmstone commented
Please ensure 100% test coverage

2021-07-07 05:12 UTC, zmstone commented on src/hocon_schema.erl
> -    Child = maps:get(H, Conf, undefined),
Not this pr’s issue, but: we need another clause to handle when Conf is not a map.

2021-07-08 10:52 UTC, closed without merging